2025-04-28 12:08:19,517 - INFO - [<module>] - Logging configured. Log file: Selenium-Logs\app_20250428_120819.log
2025-04-28 12:08:19,517 - INFO - [<module>] - Configuration loaded.
2025-04-28 12:08:19,518 - INFO - [<module>] - Utility functions defined.
2025-04-28 12:08:19,519 - INFO - [<module>] - Flask application initialized.
2025-04-28 12:08:19,519 - INFO - [<module>] - Global state variables initialized.
2025-04-28 12:08:19,604 - INFO - [<module>] - Async Telegram API functions defined.
2025-04-28 12:08:20,059 - INFO - [<module>] - Flask async routes defined.
2025-04-28 12:08:20,062 - INFO - [info] - Running on http://0.0.0.0:5000 (CTRL + C to quit)
2025-04-28 12:08:32,830 - INFO - [index] - Serving index page.
2025-04-28 12:08:37,908 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:37,910 - INFO - [initiate_upload] - [fe11322c-4e73-44fc-952d-ea8d57cbff85] Saving temporary file for 'download_page.html' to 'uploads_temp\fe11322c-4e73-44fc-952d-ea8d57cbff85_upload.tmp'
2025-04-28 12:08:37,912 - INFO - [initiate_upload] - [fe11322c-4e73-44fc-952d-ea8d57cbff85] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:37,921 - INFO - [stream_progress] - SSE connection request for upload_id: fe11322c-4e73-44fc-952d-ea8d57cbff85
2025-04-28 12:08:37,923 - ERROR - [log_exception] - Exception on /stream-progress/fe11322c-4e73-44fc-952d-ea8d57cbff85 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:38,996 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:38,997 - INFO - [initiate_upload] - [60c861ef-5432-41e5-b046-2db03098319f] Saving temporary file for 'download_page.html' to 'uploads_temp\60c861ef-5432-41e5-b046-2db03098319f_upload.tmp'
2025-04-28 12:08:39,001 - INFO - [initiate_upload] - [60c861ef-5432-41e5-b046-2db03098319f] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:39,009 - INFO - [stream_progress] - SSE connection request for upload_id: 60c861ef-5432-41e5-b046-2db03098319f
2025-04-28 12:08:39,010 - ERROR - [log_exception] - Exception on /stream-progress/60c861ef-5432-41e5-b046-2db03098319f [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:39,475 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:39,477 - INFO - [initiate_upload] - [3e68a944-4a9f-4c70-8d44-4546fba0b392] Saving temporary file for 'download_page.html' to 'uploads_temp\3e68a944-4a9f-4c70-8d44-4546fba0b392_upload.tmp'
2025-04-28 12:08:39,478 - INFO - [initiate_upload] - [3e68a944-4a9f-4c70-8d44-4546fba0b392] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:39,483 - INFO - [stream_progress] - SSE connection request for upload_id: 3e68a944-4a9f-4c70-8d44-4546fba0b392
2025-04-28 12:08:39,486 - ERROR - [log_exception] - Exception on /stream-progress/3e68a944-4a9f-4c70-8d44-4546fba0b392 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:39,666 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:39,667 - INFO - [initiate_upload] - [dbc1c768-b52a-48c5-b781-6f202760dc24] Saving temporary file for 'download_page.html' to 'uploads_temp\dbc1c768-b52a-48c5-b781-6f202760dc24_upload.tmp'
2025-04-28 12:08:39,670 - INFO - [initiate_upload] - [dbc1c768-b52a-48c5-b781-6f202760dc24] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:39,676 - INFO - [stream_progress] - SSE connection request for upload_id: dbc1c768-b52a-48c5-b781-6f202760dc24
2025-04-28 12:08:39,680 - ERROR - [log_exception] - Exception on /stream-progress/dbc1c768-b52a-48c5-b781-6f202760dc24 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:39,839 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:39,840 - INFO - [initiate_upload] - [e90e1f98-347d-4d1e-aa2a-1dac641b8c26] Saving temporary file for 'download_page.html' to 'uploads_temp\e90e1f98-347d-4d1e-aa2a-1dac641b8c26_upload.tmp'
2025-04-28 12:08:39,841 - INFO - [initiate_upload] - [e90e1f98-347d-4d1e-aa2a-1dac641b8c26] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:39,846 - INFO - [stream_progress] - SSE connection request for upload_id: e90e1f98-347d-4d1e-aa2a-1dac641b8c26
2025-04-28 12:08:39,847 - ERROR - [log_exception] - Exception on /stream-progress/e90e1f98-347d-4d1e-aa2a-1dac641b8c26 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:40,016 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:40,017 - INFO - [initiate_upload] - [94091ded-f57a-481e-975d-8e5b8602ca80] Saving temporary file for 'download_page.html' to 'uploads_temp\94091ded-f57a-481e-975d-8e5b8602ca80_upload.tmp'
2025-04-28 12:08:40,019 - INFO - [initiate_upload] - [94091ded-f57a-481e-975d-8e5b8602ca80] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:40,025 - INFO - [stream_progress] - SSE connection request for upload_id: 94091ded-f57a-481e-975d-8e5b8602ca80
2025-04-28 12:08:40,026 - ERROR - [log_exception] - Exception on /stream-progress/94091ded-f57a-481e-975d-8e5b8602ca80 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:40,205 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:40,206 - INFO - [initiate_upload] - [858a8ef0-3bb6-4771-bf2a-707b2371d68a] Saving temporary file for 'download_page.html' to 'uploads_temp\858a8ef0-3bb6-4771-bf2a-707b2371d68a_upload.tmp'
2025-04-28 12:08:40,208 - INFO - [initiate_upload] - [858a8ef0-3bb6-4771-bf2a-707b2371d68a] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:40,213 - INFO - [stream_progress] - SSE connection request for upload_id: 858a8ef0-3bb6-4771-bf2a-707b2371d68a
2025-04-28 12:08:40,214 - ERROR - [log_exception] - Exception on /stream-progress/858a8ef0-3bb6-4771-bf2a-707b2371d68a [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:40,738 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:40,743 - INFO - [initiate_upload] - [ace749e7-59bf-4b7c-a608-f3feb3b4af3d] Saving temporary file for 'download_page.html' to 'uploads_temp\ace749e7-59bf-4b7c-a608-f3feb3b4af3d_upload.tmp'
2025-04-28 12:08:40,745 - INFO - [initiate_upload] - [ace749e7-59bf-4b7c-a608-f3feb3b4af3d] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:40,750 - INFO - [stream_progress] - SSE connection request for upload_id: ace749e7-59bf-4b7c-a608-f3feb3b4af3d
2025-04-28 12:08:40,751 - ERROR - [log_exception] - Exception on /stream-progress/ace749e7-59bf-4b7c-a608-f3feb3b4af3d [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:40,825 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:40,827 - INFO - [initiate_upload] - [5eb60e96-11af-4bcc-9f29-23d41a06d0b5] Saving temporary file for 'download_page.html' to 'uploads_temp\5eb60e96-11af-4bcc-9f29-23d41a06d0b5_upload.tmp'
2025-04-28 12:08:40,828 - INFO - [initiate_upload] - [5eb60e96-11af-4bcc-9f29-23d41a06d0b5] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:40,834 - INFO - [stream_progress] - SSE connection request for upload_id: 5eb60e96-11af-4bcc-9f29-23d41a06d0b5
2025-04-28 12:08:40,834 - ERROR - [log_exception] - Exception on /stream-progress/5eb60e96-11af-4bcc-9f29-23d41a06d0b5 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:08:41,001 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:08:41,002 - INFO - [initiate_upload] - [5232da90-73c3-4bce-8258-224bf75d0cea] Saving temporary file for 'download_page.html' to 'uploads_temp\5232da90-73c3-4bce-8258-224bf75d0cea_upload.tmp'
2025-04-28 12:08:41,005 - INFO - [initiate_upload] - [5232da90-73c3-4bce-8258-224bf75d0cea] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:08:41,012 - INFO - [stream_progress] - SSE connection request for upload_id: 5232da90-73c3-4bce-8258-224bf75d0cea
2025-04-28 12:08:41,013 - ERROR - [log_exception] - Exception on /stream-progress/5232da90-73c3-4bce-8258-224bf75d0cea [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:09:07,737 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:09:07,740 - INFO - [initiate_upload] - [5bae5f0a-b09f-49d5-9fde-b6f84faf4a87] Saving temporary file for 'download_page.html' to 'uploads_temp\5bae5f0a-b09f-49d5-9fde-b6f84faf4a87_upload.tmp'
2025-04-28 12:09:07,744 - INFO - [initiate_upload] - [5bae5f0a-b09f-49d5-9fde-b6f84faf4a87] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:09:07,752 - INFO - [stream_progress] - SSE connection request for upload_id: 5bae5f0a-b09f-49d5-9fde-b6f84faf4a87
2025-04-28 12:09:07,754 - ERROR - [log_exception] - Exception on /stream-progress/5bae5f0a-b09f-49d5-9fde-b6f84faf4a87 [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:09:08,343 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:09:08,345 - INFO - [initiate_upload] - [955d4362-7eef-459f-aa4c-d2dd27a6625c] Saving temporary file for 'download_page.html' to 'uploads_temp\955d4362-7eef-459f-aa4c-d2dd27a6625c_upload.tmp'
2025-04-28 12:09:08,346 - INFO - [initiate_upload] - [955d4362-7eef-459f-aa4c-d2dd27a6625c] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:09:08,352 - INFO - [stream_progress] - SSE connection request for upload_id: 955d4362-7eef-459f-aa4c-d2dd27a6625c
2025-04-28 12:09:08,355 - ERROR - [log_exception] - Exception on /stream-progress/955d4362-7eef-459f-aa4c-d2dd27a6625c [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
2025-04-28 12:09:09,051 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:09:09,052 - INFO - [initiate_upload] - [3537e1e4-c49f-4556-ad83-4e8a838421ba] Saving temporary file for 'download_page.html' to 'uploads_temp\3537e1e4-c49f-4556-ad83-4e8a838421ba_upload.tmp'
2025-04-28 12:09:09,056 - INFO - [initiate_upload] - [3537e1e4-c49f-4556-ad83-4e8a838421ba] Temporary file saved successfully for 'download_page.html'.
2025-04-28 12:09:09,063 - INFO - [stream_progress] - SSE connection request for upload_id: 3537e1e4-c49f-4556-ad83-4e8a838421ba
2025-04-28 12:09:09,064 - ERROR - [log_exception] - Exception on /stream-progress/3537e1e4-c49f-4556-ad83-4e8a838421ba [GET]
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a async_generator.
